# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YardingDistance
                                 A QGIS plugin
 This plugin calucurates the "Yarding Distance" (average of distance from Polygon to Point).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-20
        copyright            : (C) 2024 by Sanda takeru / HOKKAIDO Regional Forest Office
        email                : takeru_sanda999@maff.go.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Sanda takeru / HOKKAIDO Regional Forest Office'
__date__ = '2024-05-20'
__copyright__ = '(C) 2024 by Sanda takeru / HOKKAIDO Regional Forest Office'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load YardingDistance class from file YardingDistance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yarding_distance import YardingDistancePlugin
    return YardingDistancePlugin()
